"use client";
import { useState } from "react";

const fields = [
  ["nom_famille","Nom"],["prenom","Prénom"],["email","Email"],["telephone","Téléphone"],
  ["discord_id","Discord ID"],["steam_id","Steam ID"],["siren","SIREN"],["siret","SIRET"],
  ["ville","Ville"],["code_postal","Code postal"],["societe","Société"],["profession","Profession"]
];

export default function Home(){
 const [values,setValues]=useState<Record<string,string>>({}); const [results,setResults]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function search(){
  const body=Object.fromEntries(Object.entries(values).filter(([,v])=>v));
  if(!Object.keys(body).length){setError("Ajoute au moins un critère.");return}
  setLoading(true);setError("");
  try{const r=await fetch("/api/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erreur API");setResults(d.results||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}
 }
 return <main><header><div className="brand"><span>◆</span> BRIX<span>HUB</span></div><div className="status">● API READY</div></header>
 <section className="hero"><div className="eyebrow">INTELLIGENCE SEARCH</div><h1>Recherche avancée,<br/><em>sans friction.</em></h1><p>Une interface moderne pour interroger votre accès BrixHub. Les clés restent côté serveur.</p></section>
 <section className="panel"><div className="panelhead"><div><b>Nouvelle recherche</b><small>Combine plusieurs critères pour affiner les résultats.</small></div><button onClick={()=>setValues({})}>Réinitialiser</button></div><div className="grid">{fields.map(([key,label])=><label key={key}>{label}<input value={values[key]||""} onChange={e=>setValues({...values,[key]:e.target.value})} placeholder={`Entrer ${label.toLowerCase()}…`}/></label>)}</div><button className="search" onClick={search} disabled={loading}>{loading?"Recherche…":"Lancer la recherche  →"}</button>{error&&<div className="error">{error}</div>}</section>
 <section className="results"><div className="resulthead"><h2>Résultats</h2><span>{results.length} profil(s)</span></div>{results.length===0?<div className="empty">Aucun résultat à afficher.<br/><small>Lance une recherche pour commencer.</small></div>:<div className="cards">{results.map((r,i)=><article key={i}><div className="avatar">{(r.prenom||"?")[0]}</div><div className="identity"><h3>{r.prenom||""} {r.nom_famille||""}</h3><p>{r.nom_utilisateur||r.email||"Profil BrixHub"}</p></div><div className="details">{Object.entries(r).filter(([k,v])=>v&&!["_sources"].includes(k)).slice(0,8).map(([k,v])=><div key={k}><small>{k.replaceAll("_"," ")}</small><span>{String(v)}</span></div>)}</div><div className="confidence">{r._confidence?`${r._confidence}% confiance`:"Résultat"}</div></article>)}</div>}</section>
 <footer>BrixHub Research · Utilisation responsable et autorisée des données</footer>
 <style jsx global>{`*{box-sizing:border-box}body{margin:0;background:#08090c;color:#f4f4f5;font-family:Inter,ui-sans-serif,system-ui}main{max-width:1180px;margin:auto;padding:28px 24px 70px}header{display:flex;justify-content:space-between;align-items:center}.brand{font-weight:900;letter-spacing:-1px;font-size:20px}.brand span{color:#8b5cf6}.status{font-size:11px;color:#a1a1aa;border:1px solid #27272a;padding:7px 11px;border-radius:99px}.status:first-letter{color:#22c55e}.hero{text-align:center;padding:90px 0 55px}.eyebrow{color:#8b5cf6;font-size:11px;font-weight:800;letter-spacing:3px}.hero h1{font-size:64px;line-height:1;letter-spacing:-4px;margin:18px 0}.hero em{font-style:normal;color:#a78bfa}.hero p{color:#a1a1aa;max-width:600px;margin:auto;line-height:1.7}.panel{background:#101116;border:1px solid #25262d;border-radius:22px;padding:26px;box-shadow:0 20px 70px #0006}.panelhead{display:flex;justify-content:space-between;margin-bottom:24px}.panelhead b{display:block}.panelhead small{display:block;color:#71717a;margin-top:5px}.panelhead button{background:none;color:#a1a1aa;border:0}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}label{font-size:11px;color:#a1a1aa;font-weight:700}input{display:block;width:100%;margin-top:7px;background:#08090c;border:1px solid #292b33;color:white;border-radius:10px;padding:12px;outline:none}input:focus{border-color:#8b5cf6}.search{margin-top:22px;width:100%;padding:14px;border:0;border-radius:11px;background:#8b5cf6;color:white;font-weight:800;cursor:pointer}.search:disabled{opacity:.5}.error{margin-top:14px;color:#fca5a5}.results{margin-top:60px}.resulthead{display:flex;justify-content:space-between;align-items:center}.resulthead h2{font-size:24px}.resulthead span{color:#71717a;font-size:12px}.empty{border:1px dashed #292b33;border-radius:18px;text-align:center;padding:70px;color:#71717a}.empty small{line-height:3}.cards{display:grid;gap:14px}.cards article{position:relative;display:grid;grid-template-columns:50px 220px 1fr auto;gap:18px;align-items:start;padding:20px;background:#101116;border:1px solid #25262d;border-radius:16px}.avatar{width:44px;height:44px;border-radius:12px;background:#27203e;color:#c4b5fd;display:grid;place-items:center;font-weight:900}.identity h3{margin:2px 0 5px}.identity p{margin:0;color:#71717a;font-size:12px}.details{display:flex;gap:18px;flex-wrap:wrap}.details div{min-width:110px}.details small{display:block;color:#71717a;text-transform:capitalize;font-size:9px}.details span{display:block;margin-top:4px;font-size:12px;overflow-wrap:anywhere}.confidence{color:#a78bfa;font-size:11px;white-space:nowrap}footer{text-align:center;color:#52525b;font-size:11px;margin-top:70px}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}.hero h1{font-size:44px}.cards article{grid-template-columns:44px 1fr}.details,.confidence{grid-column:1/-1}}`}</style></main>
}